### ISSUE TITLE
Request for Assignment: Refactor Discord Bot to Use Express.js

### ISSUE THREAD

**Issue by ag21o9** [jinx-vi-0/DDoL#1]
### Description
Issue Summary: I encountered an error in my Discord bot: "Used disallowed intents." This error is triggered when the bot attempts to use intents that are not enabled in the Discord Developer Portal. As a result, the bot fails to start properly and emits an unhandled error event.

To resolve this issue, I propose to refactor the bot to use Express.js. This will allow the bot to maintain a consistent server connection and help prevent similar issues in the future.
### Proposed Changes:

Implement the Discord bot using Express.js to handle server connections.
Ensure that the required intents are correctly configured in the Discord Developer Portal.
I would like to request to be assigned to this task to address the error and improve the bot's functionality.

Thank you for considering my request!

**Comment by BhairabMahanta** [comment]
Could you let us know what new intent is causing that? 
I forked the bot and its working well with all the commands. If i get to the root of the problem, I'm certain i can fix it!

Screenshots are appreciated.

**Comment by adarsh-site** [comment]
bot is working perfectly. you can checkout its functionalities in the leetcode channel of this [discord server](https://discord.gg/C53MSUEbN3)

**Comment by ag21o9** [comment]
assign me to convert the code to express form, it will be easy to maintain and add new features, I will not take much time

**Comment by adarsh-site** [comment]
Assigned @ag21o9 .

No need to rush. Take your time. Feel free to reach out on Discord if you need assistance.

**Comment by prisha-sh** [comment]
Hey I'm interested please assign me, ill share my proposed solution as soon as u ping me !!
