### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by rajatsinghal02** [jinx-vi-0/DDoL#11]
@jinx-vi-0 I want to add contributing.md file to the GitHub repo. Please assign this issue to me.

**Comment by code-killer0** [comment]
Please assign this issue to me.

**Comment by Charul00** [comment]
@rajatsinghal02 can you please assign to me and add level tag

**Comment by code-killer0** [comment]
Hi @jinx-vi-0 your contribute.md 
The Page will something look like that :

1. New Contributor Guide part 
2. Getting Started section
3. Issues
   3.1 Create a New Issue
   3.2 Solve an Issue
4. Making Changes
    4.1 Make Changes in the UI
    4.2 Make Changes in a Codespace
    4.3 Make Changes Locally
5. Pull Request

And adding some more stuff according what this repo wants and points you add on tasks.
Hope so you will assign and I will start working on it 

Add gssoc and hacktober-accepeted tag

**Comment by adarsh-site** [comment]
refer issue #19 
submit a single pr with complete documentation update.
