### ISSUE TITLE
Adding All Contributors' Profile Photos

### ISSUE THREAD

**Issue by souvikpramanikgit** [jinx-vi-0/DDoL#14]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared

Hey! @jinx-vi-0 , I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

I will add this type of Live Contributor Profile Photos in it
![image](https://github.com/user-attachments/assets/88f8a9fb-ead6-4060-ab8d-0c0d4111525c)

**Comment by adarsh-site** [comment]
refer issue #19 

submit a single pr with complete documentation update.
