### ISSUE TITLE
Migration from prefix commands to slash commands for better compatibility with Discord.

### ISSUE THREAD

**Issue by rishabh7923** [jinx-vi-0/DDoL#15]
## Summary

Since Discord has rolled out slash commands, it is recommended by Discord that developers use them as much as possible. This will make it easier for developers to verify their bots during the verification process. Slash commands have numerous benefits such as

- Integration with the Discord client interface.
- Automatic command detection and parsing of the associated options/arguments.
- Typed argument inputs for command options, e.g. "String", "User", or "Role".
- Validated or dynamic choices for command options.
- In-channel private responses (ephemeral messages).
- Pop-up form-style inputs for capturing additional information.

It will be easier for users to simply use a slash and get all the suggestions right in their command window. It is also very efficient, as it does not monitor every single message sent in the server.

**I would like to request that I be assigned this task with the GSSoC hashtag and the task level.**

**Comment by adarsh-site** [comment]
Assigned @rishabh7923

**Comment by adarsh-site** [comment]
Hey @rishabh7923, could you please update the documentation to reflect the latest changes?

**Comment by rishabh7923** [comment]
Yes sure
