### ISSUE TITLE
Improve Bot Leetcode Link Message UI

### ISSUE THREAD

**Issue by ParasY1724** [jinx-vi-0/DDoL#18]
**Desciption:**
Using Discord EmbbedBuilder enhancing ui of message to send
Example:
![Screenshot From 2024-10-05 20-32-43](https://github.com/user-attachments/assets/15e0f2b1-0889-4d92-b64e-dc62f553ec7a)

**Comment by adarsh-site** [comment]
This looks interesting. Assigned @ParasY1724

**Comment by adarsh-site** [comment]
Good work!
