### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by adarsh-site** [jinx-vi-0/DDoL#19]
Add or update all the necessary documentation related issue.
- update readme
- add contribution file
- add code of conduct
etc.

**Comment by yashksaini-coder** [comment]
I would like to work  on this issue. Assign it to me @jinx-vi-0. I can improve the README, with different sections brief guides points, action workflow for contributors list update in real time, with scheduled cron job and after every commit.

Will work to fulfill all the above mentioned requirements & meet criteria in one PR only.

So will you assign this issue to me as a GSSOC contributor, @jinx-vi-0

**Comment by adarsh-site** [comment]
This is an open issue anyone can take it. But make sure to send me a ss of your readme before submitting a pr.

**Comment by yashksaini-coder** [comment]
> This is an open issue anyone can take it. But make sure to send me a ss of your readme before submitting a pr.

okh I understand will drop a scr in discord, so will you assign this issue to me

**Comment by Vaishnavigowda27** [comment]
Can you add me I would to solve this issue

**Comment by nidhi2026** [comment]
@jinx-vi-0 

I have made listed some changes to the readme
- Added all contributor's photo
- Added setup of discord bot
- Added steps for contributing

If it looks fine, can you assign this issue to me.

![image](https://github.com/user-attachments/assets/eae47d3a-52d0-4f1c-9fa9-1ef4c4107af4)
![image](https://github.com/user-attachments/assets/4cd06f32-cdc7-45c7-b22a-18dc0efdd1d0)
![image](https://github.com/user-attachments/assets/aad09539-8ed0-4f0f-9bd8-e559ac1af6dd)
![image](https://github.com/user-attachments/assets/94f626c4-8d34-40ba-a914-876c03916e52)

**Comment by adarsh-site** [comment]
@nidhi2026 submit a pr asap.

**Comment by yashksaini-coder** [comment]
> @nidhi2026 submit a pr asap.

Hi @jinx-vi-0 can you please check this PR #29

**Comment by nidhi2026** [comment]
@jinx-vi-0 I have submitted a pr for this, kindly check if it's fine
