### ISSUE TITLE
Refactor Discord Bot to Use Command Handler with Keep-Alive Support

### ISSUE THREAD

**Issue by BhairabMahanta** [jinx-vi-0/DDoL#2]
**Summary**:
I propose refactoring the Discord bot code to implement a modular command handler system, which will greatly improve scalability, ease of maintenance, and extendability. The current code also includes a keep-alive feature for server hosting, which will be preserved and optimized in this refactor.

**Proposed Changes:**

1. **Command Handler Implementation:**
   - Refactor command logic into separate files under appropriate folders (e.g., `/commands/general`, `/commands/admin`).
   - Implement recursive loading of commands from multiple folders for better organization.
   
2. **Keep-Alive Feature:**
   - Ensure that the existing Express.js-based keep-alive function remains active and works seamlessly with the new modular system.
   - Optionally, enhance the keep-alive logic to include health checks (e.g., checking bot status, uptime, etc.).

3. **Logging and Error Handling:**
   - Implement detailed logging (including `console.log` statements) for command loading, errors, and execution.
   - Improve error handling for command loading (e.g., gracefully handling broken or incorrectly formatted commands).

4. **Folder Structure and Scalability:**
   - Use a well-defined folder structure to manage commands, events, and other logic:
     - `/commands/`: Organize commands into categories (e.g., `general`, `admin`).
     - `/events/`: For handling events like `ready`, `messageCreate`.
     - `/util/`: For utility functions (e.g., keeping utility functions separate from bot logic).
![ddol](https://github.com/user-attachments/assets/3079bd1e-1d7d-4f65-b41f-bf2330df12dd)
5. **Command Arguments and Aliases:**
   - Introduce support for command aliases (e.g., `!help` can also be triggered with `!h`).
   - Add argument validation for commands to handle user input gracefully and reduce runtime errors.

6. **Command Cooldowns:**
   - Can further keep spaces to implement cooldowns and role based commands.

9. **Async/Await and Promises:**
   - Refactor the command logic to consistently use `async/await` for commands that involve asynchronous operations (e.g., fetching data from APIs) for more readable and maintainable code.

### **Why the Change?**

1. **Improved Maintainability, Scalability, Improved Error Handling, Performance Optimizations    **

2. **Automated Help:**
   - Can Later automate the help command reducing the need for manual updates every time a new command is added, ensuring the help menu is always up-to-date.

 **Database Integration:**
   - If needed in the future, the refactor can easily support the addition of databases (e.g., MongoDB) for features like tracking command usage, saving user data, etc.

---

### **Request:**
- I would like to request to be assigned this task 
- with gssoc hashtag and level of the task hashtags
- I would proceed with the changes to enhance the bot's functionality and maintainability. This refactor will make the bot much easier to extend, reduce bugs, and improve the overall performance.

**Comment by adarsh-site** [comment]
Assigned @BhairabMahanta 

I'll add the level after reviewing your pull request. You can start working on this issue.

**Comment by prisha-sh** [comment]
Hey I'm interested please assign me, ill share my proposed solution as soon as u ping me !!

**Comment by BhairabMahanta** [comment]
> Hey I'm interested please assign me, ill share my proposed solution as soon as u ping me !!

please do. @prisha-sh
