### ISSUE TITLE
[Feature] : Add Github Greeting Bot ( Level 1)

### ISSUE THREAD

**Issue by ghost** [jinx-vi-0/DDoL#23]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by adarsh-site** [comment]
Assigned @KiranBaliga

**Comment by ghost** [comment]
@jinx-vi-0 Please review the PR and action accordingly. Please duplicate the labels in the PR as well. Thank you!
