### ISSUE TITLE
Bug Fixing of Badges : 0 + Fetching User Deatils + User Profile Display Message UI Enchancement  

### ISSUE THREAD

**Issue by ParasY1724** [jinx-vi-0/DDoL#25]
**Description:**
On `;user <username>` cmd it fetches only contest details and no badges is always 0 even i have some ,
![Screenshot From 2024-10-06 11-47-49](https://github.com/user-attachments/assets/b5fad3ad-6cec-48d5-9228-cf7becabc8bf)

# Suggest Implementation:
- Fetching Name, Country , Ratings , Problems Solved Stats,Badges
- Improving UI using EmbedBuilder of discord

## Suggested Design:
![Screenshot From 2024-10-06 11-50-17](https://github.com/user-attachments/assets/7e03dc11-19fb-4e9b-8065-59a010f228a8)

**Comment by ParasY1724** [comment]
Please Assign this task to me

**Comment by adarsh-site** [comment]
Assigned @ParasY1724

**Comment by adarsh-site** [comment]
Awesome 👌

**Comment by nidhi2026** [comment]
@ParasY1724 
In that ss, easy count is out of total easy problem submission by that user not total easy problems. like in leetcode we have ac easy count out of total easy problems.

**Comment by ParasY1724** [comment]
> @ParasY1724 
> In that ss, easy count is out of total easy problem submission by that user not total easy problems. like in leetcode we have ac easy count out of total easy problems.

@nidhi2026 it's accepted/ (accepted + partial submission)

**Comment by adarsh-site** [comment]
guys please discuss it over discord. you can find a thread of this repo.
