### ISSUE TITLE
[BUG] Error Fetching User Info for Unparticipated Leetcode Users and incorect badge display 

### ISSUE THREAD

**Issue by nidhi2026** [jinx-vi-0/DDoL#30]
### What happened ?
When attempting to fetch user information for valid Leetcode users (e.g., inurownhands), an error occurs with the message:
`Error fetching user info: TypeError: Cannot read properties of null (reading 'attendedContestsCount')`

![image](https://github.com/user-attachments/assets/40822a2c-816e-4189-b83b-fbf3663d143e)

Despite the user being valid, the bot throws an error and fails to retrieve user info., it should rather give 0 as contest value.

![image](https://github.com/user-attachments/assets/a1831c8f-6f86-46a8-a4d6-f2535540e6c8)

 When fetching user information like for [fjzzq2002](https://leetcode.com/u/fjzzq2002/) from Leetcode, the bot displays the badge as [object Object] instead of showing the actual badge. This issue occurs for users who have valid badges, but the bot is not handling the badge display correctly in Discord.
![img](https://github.com/user-attachments/assets/4c72305a-b6bc-4e95-a901-a77b73dab2c5)

**Comment by nidhi2026** [comment]
@jinx-vi-0 
I want to work on this bug. Can you assign it to me.
I am a GSSOC-ext contributor

**Comment by adarsh-site** [comment]
Already Done.
