### ISSUE TITLE
[BUG] Consecutive Days Streak Attribute Not Available in User Profile

### ISSUE THREAD

**Issue by nidhi2026** [jinx-vi-0/DDoL#33]
### What Happenend ?
![image](https://github.com/user-attachments/assets/4c1c4750-ae8a-41b2-988f-66cad22d0540)

In code we are accessing `consecutiveDays` in `streakInfo`, but we have no option for it in [leetcode-query](https://github.com/JacobLinCool/LeetCode-Query/blob/e7b068af2b3b7f75eeb11aa89eaf78b00133311b/src/leetcode-types.ts)

![image](https://github.com/user-attachments/assets/6f999b0d-de75-4a2b-8d9d-879699358b88)

that results in same response every time (functionality doesn't work as expected).

An issue has been made for creating streak where the result was:
![image](https://github.com/user-attachments/assets/71e5dcb9-f16d-4ece-acd9-d5675465372a)

I have now tried for the same user in [issue](https://github.com/jinx-vi-0/DDoL/pull/10) 

![image](https://github.com/user-attachments/assets/ffe86a4d-8909-4993-868c-2f403239ab0d)

Rather it should look like: (for user's max streak for current year)
https://leetcode.com/u/JB_Mugundh/
![image](https://github.com/user-attachments/assets/eb07630a-20b9-4cab-b217-6227096fe274)

**Comment by nidhi2026** [comment]
@jinx-vi-0 
Can you assign this bug to me

**Comment by adarsh-site** [comment]
You don't need to show the max streak. It should be the current streak.

**Comment by nidhi2026** [comment]
![image](https://github.com/user-attachments/assets/c2754263-cd00-43e4-a49e-34b8349ca1a0)
@jinx-vi-0 
If this is fine, then I will make a pr for it

**Comment by nidhi2026** [comment]
@jinx-vi-0 I have made a pr for this
