### ISSUE TITLE
[feat]: Improving bot.js for faster responses, and have enhanced error handling

### ISSUE THREAD

**Issue by Yash-Vashishth** [jinx-vi-0/DDoL#35]
Hi @jinx-vi-0 !! Your bot design is amazing !! Though it is concise I think it needs a lot of changes to function in a refined manner.

Here is a summary of the changes I will make- better code organization, enhanced error handling, modular functions for different command handlers, and improved readability.

A long and boring form:-
1.Separate Concerns: Split large functions into smaller, more manageable ones. For instance, the messageCreate event handler could be broken down into separate handlers for each command.
2. Modularization: Create separate files or modules for different functionalities like command handling, utility functions, etc.
3. Cache frequently used data to reduce API calls and improve response times.
4. Optimize the fetchLeetCodeProblems function to handle large datasets efficiently.
5. Follow consistent naming conventions and code formatting for better readability.
6. Using ESLint or Prettier to enforce consistent coding standards.

**Comment by Yash-Vashishth** [comment]
Also - pls add the hacktoberfest , gssoc-ext , level 3 tag to this code since I will need to commit a lot of changes 
Thnks,
Yash Vashishth
(Contributor, GSSoC'24(Extd) and Hacktoberfest)

**Comment by rishabh7923** [comment]
I am working on point 1 and point 2, soon will do pr

**Comment by Yash-Vashishth** [comment]
@rishabh7923 i have raised the issue for this so I believe i have the right to raise the pr for them 

And I already have the improved code so no need for you to do pr

**Comment by rishabh7923** [comment]
I understand that but the issue to which i am assigned already has these things included so i was just letting you know to avoid future conflict. no issues if you still wanna continue

**Comment by Yash-Vashishth** [comment]
Hi @jinx-vi-0!! Please atleast please merge this commit to the main branch and add labels. I have made many changes to the code
