### ISSUE TITLE
Add the CONTRIBUTING.md file to the repository

### ISSUE THREAD

**Issue by Brijeshthummar02** [jinx-vi-0/DDoL#39]
Problem Description: Is it possible to add the CONTRIBUTING.md file to the repository? Once established, this file will provide clear guidance to additional contributors on how to best support the project, including steps to customize development environments, coding standards, and procedures for submitting pull requests This will help streamline the donation process and encourage their greater participation .

you can assign me to the task.

**Comment by adarsh-site** [comment]
No more documentation issue.
