### ISSUE TITLE
Create Contributing.md File for Clear Contributor Guidelines

### ISSUE THREAD

**Issue by Jyothishree2k5** [jinx-vi-0/DDoL#54]
The project currently lacks a Contributing.md file, which makes it difficult for new contributors to understand the contribution process. Adding this file with clear guidelines will make onboarding smoother and encourage more contributions. can you please assign it to me under gssoc and hacktoberfest

**Comment by adarsh-site** [comment]
we're no longer accepting documentation changes. If you still want to contribute, you are good to go, but we'll not add any level to it.
