### ISSUE TITLE
Daily Question Reminder Not Working 

### ISSUE THREAD

**Issue by ParasY1724** [jinx-vi-0/DDoL#55]
**Describe the bug**
I was working on #53 , there is code for daily-question reminder at 6:00 AM but the code didn't work clearly =>
`const channel = client.channels.cache.get(process.env.CHANNEL_ID);`
But Thing is we have to send message to all channels for which our bot is Authicated , line no 8 uses process.env.CHANNEL_ID which is wrong as CHANNEL_ID in env specifies server not channel (Text) 
so we get channel = undefined
and failed to send message occurs as below

![Screenshot From 2024-10-15 02-20-04](https://github.com/user-attachments/assets/11bf1142-9085-4eff-b9ab-d19741e9a312)

**Comment by ParasY1724** [comment]
Please Assign this task to me

**Comment by adarsh-site** [comment]
![image](https://github.com/user-attachments/assets/a6a357a1-273d-4ac3-8bb9-282c9e8bd8d5)

working perfectly

**Comment by ParasY1724** [comment]
> working perfectly

**Please Add your bot to another server and try it** , in your case channel_id in env is same as your channel so **only you are** receiving it .
Like i have added your bot in my server and i didn't receive it.

line no 10 in ready.js
`         const channel = client.channels.cache.get(process.env.CHANNEL_ID);
`
