### ISSUE TITLE
Update README to Include Participation and Contribution Guidelines.

### ISSUE THREAD

**Issue by Snehshishdutta** [jinx-vi-0/DDoL#65]
I would like to enhance the README file by including the following updates:

Participation Table:

Add a table to highlight our participation in Hacktoberfest and GirlScript Summer of Code (GSSoC). The table should include details like the year of participation, the event name, and any relevant notes.
Example Table Structure:
![image](https://github.com/user-attachments/assets/ca3bbc16-8ba2-4065-91b3-1d54da5d2e4a)

How to Contribute Section:

Expand the "How to Contribute" section to provide clear and detailed guidelines for potential contributors.
Include steps for:
Forking the Repository: Explain how to create a personal copy of the repo.
Creating a Branch: Instruct contributors on how to create a new branch for their work.
Making Changes: Describe how to make and test changes.
Submitting a Pull Request: Provide guidelines on how to submit their changes and any necessary checks to complete beforehand.
Encourage contributors to review existing issues or propose new features.
Benefits:

This update will provide clear information about our participation in important events and help new contributors understand how they can get involved, ultimately fostering a more welcoming and informative environment. So can u assign this issue to me.

**Comment by adarsh-site** [comment]
No more Documentation Update.
