### ISSUE TITLE
[New Feature] User streak command

### ISSUE THREAD

**Issue by J-B-Mugundh** [jinx-vi-0/DDoL#9]
Add a feature that allows users to track their LeetCode problem-solving streaks.

- Command: streak username
- Description: Fetches and displays the number of consecutive days the user has solved a problem on LeetCode.

**Comment by J-B-Mugundh** [comment]
@sanjay-kv @jinx-vi-0 Please assign this issue to me. Also, add gssoc-extd and hacktoberfest labels.

**Comment by adarsh-site** [comment]
Assigned @J-B-Mugundh

**Comment by J-B-Mugundh** [comment]
Thanks @jinx-vi-0! I've worked on it and raised a PR #10. Please review it and let me know if it requires any changes!
